FROM python:3.11-slim

RUN apt-get update && apt-get install -y bash git && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir dbt-postgres==1.8.2

WORKDIR /usr/app

CMD ["tail", "-f", "/dev/null"]
